---
title: "20200915"
author: "Yu-Wen Vanessa CHEN"
date: "2020/09/22"
output:  
  "html_document":
   theme: united
   highlight: tango
   toc: true
   toc_depth: 3
   toc_float: true
   number_sections: false
   code_folding: show
    # ioslides_presentation 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Install "vegan"

*What is "vegan"?*
 
 - Provides tools for descriptive community ecology.
 - Contain tools for diversity analysis
```{r class.source = "fold-hide",  eval=FALSE}
install.packages('vegan')
library('vegan')
```

## Reading

- Example
Programming language needed in the workplace in 2019

## Data

```{r,  eval=FALSE}
library(readxl)
read_excel('D:/臺灣大學/海研所/R/Working directory/20200915/Programming language needed in the workplace.xlsx') 
language<-read_excel('D:/臺灣大學/海研所/R/Working directory/20200915/Programming language needed in the workplace.xlsx')
```

Ranking|Language|Avg(%)
-|-----|----
1|Python|74.5
2|R|55.1
3|SQL|54.3
4|Spark|28.6
5|Hadoop|27.5
6|Java|24.6
7|Tableau|19.8
8|AWS|19.4
9|SAS|17.9
10|Hive|14.7

## Plot
```{r,  eval=FALSE,  tidy=TRUE}
language <- read.table('D:/臺灣大學/海研所/R/Working directory/20200915/Programming language needed in the workplace.txt', header=T, sep='\t', dec='.')
barplot(language$Avg, main="Top 10 Programming language (Hale, 2019)", horiz=TRUE, names.arg=language$Language, cex.names=0.7, las=1)
```
